version: '3.4'
services:
  pedelogo.catalogo.api:
    image: kubedevio/pedelogo-catalogo:v1.0.0
    ports:
      - 8080:80
    environment:
      Mongo__Host: mongodb
      Mongo__User: mongouser
      Mongo__Password: mongopwd 
      Mongo__Port: 27017
      Mongo__DataBase: admin
    volumes:
      - "./logs/api:/log"
    depends_on:
      - mongodb
    networks: 
      - pedelogo_network 
  mongodb:
    image: mongo:4.2.8
    networks: 
      - pedelogo_network 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser 
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  loki:
    image: grafana/loki:2.0.0
    ports: 
      - "3100:3100"
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks: 
      - pedelogo_network
  promtail:
    image: grafana/promtail:2.0.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - "./promtail/config.yml:/etc/promtail/config.yml"
      - "./logs/api:/logs/api"
      - "./tmp:/tmp"
    networks: 
      - pedelogo_network
    ports:
      - "9080:9080"   
networks: 
  pedelogo_network:
    driver: bridge