apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedelogo-prometheus-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedelogo-prometheus
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
      labels:
        app: pedelogo-prometheus
    spec:
      containers:
      - name: pedelogo-prometheus
        image: kubedevio/pedelogo-catalogo:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: Mongo__User
            value: mongouser 
          - name: Mongo__Password
            value: mongopwd 
          - name: Mongo__Host 
            value: pedelogo-prometheus-mongodb-service
          - name: Mongo__Database
            value: admin