apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec: 
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: guilherme.maas@gmail.com 
    privateKeySecretRef: #Secret que irá armazenar a chave privada
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik