apiVersion: v1
kind: Pod
metadata:
  name: meupodverde
  labels:
    app: nginx
    versao: verde
spec:
  containers:
    - name: meucontainer
      image: kubedevio/nginx-color:green
      resources:
        requests:
          ephemeral-storage: 100Mi
        limits:
          ephemeral-storage: 100Mi