apiVersion: v1
kind: Pod
metadata:
  name: meupodazul
  labels:
    app: nginx
    versao: azul
spec:
  containers:
    - name: meucontainer
      image: kubedevio/nginx-color:blue
      resources:
        requests:
          ephemeral-storage: 100Mi
        limits:
          ephemeral-storage: 100Mi