apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-loadbalancer
spec:
  selector:
    matchLabels:
      app: api-loadbalancer
  template:
    metadata:
      labels:
        app: api-loadbalancer
    spec:
      containers:
      - name: api-loadbalancer
        image: kubedevio/api-conversao:v1-machine-name