apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-container
spec:
  selector:
    matchLabels:
      app: resource-container
  template:
    metadata:
      labels:
        app: resource-container
    spec:
      containers:
        - name: resource-container
          image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "500m"
          command:
            - "/consumer"
            - "-port"
            - "9191"
          ports:
            - containerPort: 9191
---
apiVersion: v1
kind: Service
metadata:
  name: resource-container-service
spec:
  selector:
    app: resource-container
  ports:
    - port: 9292
      targetPort: 9191