global:
route: #Se o alerta em "fire" disparar e não cair na regra de nenhuma route, vai ser alarmardo por aqui.
  receiver: default
  group_by: ['alertname'] 
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 10m
  routes:
    - receiver: mongodb-alerts
      match:
        team: mongodb
    - receiver: pedelogo-api-alerts
      match:
        team: pedelogo-api      
receivers:
  - name: default
    webhook_configs:
      - url: 'http://pruu.herokuapp.com/dump/wpwebhookdefault'
  - name: mongodb-alerts
    webhook_configs:
      - url: 'http://pruu.herokuapp.com/dump/wpwebhookdefault'
  - name: pedelogo-api-alerts    
    webhook_configs:
      - url: 'http://pruu.herokuapp.com/dump/wpwebhookdefault'