groups:
  - name: mongodb
    rules:
      - alert: mongodb-alta-taxa-query
        expr: rate(mongodb_op_counters_total{type="query"}[1m]) > 1
        for: 10s
        labels:
          team: mongodb
        annotations:
          summary: "Número de buscas está alta no mongodb"
          description: "0 Número de operações do tipo {{$labels.type}} no mongoDB {{$labels.instance}} está alta"
  - name: pedelogo-api
    rules:
      - alert: web-api-alta-taxa
        expr: rate(http_requests_received_total[1m]) > 1
        for: 30s
        labels:
          team: pedelogo-api
        annotations:
          summary: "Taxa de requisições acima do normal em: {{$labels.instance}}"
          description: "{{$labels.instance}} está com uma taxa de requests alta: {{$value}}"