scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: [localhost:9090]
        labels:
          grupo: 'Prometheus'

  - job_name: ApiProduto
    static_configs:
      - targets: ['13.89.198.26']
        labels:
          grupo: 'AspNetCore'